# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-14 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('fecha_termino', models.DateTimeField()),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Equipo.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalEquipoHistoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('hw', models.CharField(max_length=100)),
                ('sw', models.CharField(max_length=100)),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Equipo.Equipo')),
            ],
        ),
    ]
