# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Personal', '0002_auto_20180619_0906'),
        ('Equipo', '0010_auto_20180703_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(auto_now=True)),
                ('fecha_termino', models.DateTimeField()),
                ('equipos', models.ManyToManyField(to='Equipo.Equipo')),
                ('personas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Personal.Personas')),
            ],
        ),
    ]
