# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0002_auto_20180718_0801'),
        ('PersonalEquipo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalequipo',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Personal.Persona'),
        ),
        migrations.AddField(
            model_name='personalequipohistoria',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Personal.Persona'),
        ),
    ]
