# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalEquipo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalequipo',
            old_name='personas',
            new_name='persona',
        ),
    ]
