# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalEquipo', '0003_auto_20180704_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalequipo',
            name='fecha_termino',
            field=models.DateTimeField(),
        ),
    ]
