# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalEquipo', '0005_auto_20180704_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalequipo',
            name='atrasado',
            field=models.BooleanField(default=False),
        ),
    ]
