# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalEquipo', '0009_auto_20180705_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalequipo',
            name='atrasado',
        ),
    ]
