# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-14 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=30, unique=True)),
                ('serieEntel', models.CharField(max_length=30, null=True, unique=True)),
                ('serieEnap', models.CharField(max_length=30, null=True, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('clase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Equipo.Clase')),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('clases', models.ManyToManyField(to='Equipo.Clase')),
            ],
        ),
        migrations.CreateModel(
            name='MAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17, unique=True)),
                ('descripcion', models.CharField(max_length=30, null=True)),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Equipo.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='hardware',
            field=models.ManyToManyField(to='Equipo.Hardware'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='software',
            field=models.ManyToManyField(to='Equipo.Software'),
        ),
    ]
