# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-23 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='serieEnap',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='serieEntel',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
