# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Softeware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
