# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0002_softeware'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Softeware',
            new_name='Software',
        ),
    ]
