# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-25 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0002_auto_20180723_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='serieEntel',
            new_name='serieProveedor',
        ),
    ]
