# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0007_auto_20180703_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mac',
            name='mac',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
