# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0009_auto_20180703_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='hardware',
        ),
        migrations.AddField(
            model_name='equipo',
            name='hardware',
            field=models.ManyToManyField(to='Equipo.Hardware'),
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='software',
        ),
        migrations.AddField(
            model_name='equipo',
            name='software',
            field=models.ManyToManyField(to='Equipo.Software'),
        ),
    ]
