# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdc', models.CharField(max_length=8, unique=True)),
                ('area', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_secundario', models.CharField(max_length=30, null=True)),
                ('apellido_paterno', models.CharField(max_length=30, null=True)),
                ('apellido_materno', models.CharField(max_length=30, null=True)),
                ('Gestor', models.BooleanField(default=False)),
                ('Gestionado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Personal.Persona')),
                ('GestorIdentificador', models.ManyToManyField(related_name='_persona_GestorIdentificador_+', to='Personal.Persona')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Personal.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='puesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Personal.Puesto'),
        ),
    ]
