# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 17:42
from __future__ import unicode_literals

import Personal.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CDC', models.CharField(max_length=8, unique=True, validators=[Personal.validators.value_is_correct_expression_regular])),
                ('Area', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Puesto', models.CharField(max_length=30, unique=True, validators=[Personal.validators.value_is_lowercase])),
            ],
        ),
    ]
