# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-18 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='Gestionado',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nombre_secundario',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='GestorIdentificador',
        ),
        migrations.AddField(
            model_name='persona',
            name='GestorIdentificador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Personal.Persona'),
        ),
    ]
