# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CDC', models.IntegerField(unique=True)),
                ('Area', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
