# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='GestorIdentificador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Personal.Personas'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='Gestor',
            field=models.BooleanField(default=False),
        ),
    ]
