# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-15 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdc', models.CharField(max_length=8, unique=True)),
                ('area', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
