# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 13:47
from __future__ import unicode_literals

import Personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puestos',
            name='Puesto',
            field=models.CharField(max_length=30, unique=True, validators=[Personal.models.value_is_lowercase]),
        ),
    ]
