# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0002_auto_20180718_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='GestorIdentificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Personal.Persona'),
        ),
    ]
