# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-15 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0002_clase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clase',
            new_name='Area',
        ),
    ]
