# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 16:54
from __future__ import unicode_literals

import Personal.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0002_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='CDC',
            field=models.IntegerField(unique=True, validators=[Personal.validators.value_is_number]),
        ),
    ]
