# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-15 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0003_auto_20180714_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_secundario', models.CharField(max_length=30, null=True)),
                ('apellido_paterno', models.CharField(max_length=30, null=True)),
                ('apellido_materno', models.CharField(max_length=30, null=True)),
                ('Gestor', models.BooleanField(default=False)),
                ('GestorIdentificador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Personal.Persona')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Personal.Area')),
                ('puesto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Personal.Puesto')),
            ],
        ),
    ]
